### ISSUE TITLE
mobile import

### ISSUE THREAD

**Issue by loranger** [meliharvey/threescaper#1]
Awesome ! 
Thank you so much for this wonderful project.
Taking a walk at my towns is a dream that finally comes true, thanks to you… But.
I build my towns on my phone, or on my mac, using the ios version of townscaper.
Do you know if there's a way to export my towns to .obj files ?

Maybe by converting the town hashes ?

**Comment by meliharvey** [comment]
If you export town hashes and load into a desktop version you can then export as an OBJ. Otherwise I don't know as I've never used the mobile version.

**Comment by loranger** [comment]
Thanks for your support.
That's quite the solution someone gave me [on reddit](https://www.reddit.com/r/Townscaper/comments/srg77x/mobile_to_obj/). 
I'll find a PC and convert my towns.

Anyway, thank you so much for this awesome tool !
